### ISSUE TITLE
[tg tool]  low coverage for terminator_02-2

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/HornLauncher#19]
For https://github.com/sosy-lab/sv-benchmarks/blob/99d37c5b4072891803b9e5c154127c912477f705/c/loops/terminator_02-2.c
coverage is expected to be higher and covered condition line 26 `while(x<100 && z>100)`
![image](https://user-images.githubusercontent.com/16242682/130816740-e91679ad-c0ff-414d-b61f-3f1d65556cc3.png)

[terminator_02-2.smt2.txt](https://github.com/izlatkin/HornLauncher/files/7048056/terminator_02-2.smt2.txt)
[log.txt](https://github.com/izlatkin/HornLauncher/files/7048058/log.txt)

**Comment by grigoryfedyukovich** [comment]
should be fixed

**Comment by izlatkin** [comment]
It is partially fixed, looks like lines 35-40 should be covered
![image](https://user-images.githubusercontent.com/16242682/132239866-c3e9019b-ef69-4e1e-aca2-7d49c1251354.png)


all 4 tests contains only
`static const int inp_14364[] = {};`

it is expected both
`static const int inp_14364[] = {1};` and `static const int inp_14364[] = {0};`

**Comment by izlatkin** [comment]
very similar case with https://github.com/sosy-lab/sv-benchmarks/blob/master/c/loops/trex02-2.c
![image](https://user-images.githubusercontent.com/16242682/132243209-38321634-cfe4-4dd5-ad6a-bc536c046968.png)

**Comment by izlatkin** [comment]
Need to find SeaHorn option to increase # of rules

**Comment by grigoryfedyukovich** [comment]
I believe I fixed the issue (for `terminator_02`).

**Comment by izlatkin** [comment]
Strange results:
![image](https://user-images.githubusercontent.com/16242682/133645630-b13f32cc-f7bb-4c10-ab92-f2f299482bae.png)
[terminator_02-2.smt2_1.txt](https://github.com/izlatkin/HornLauncher/files/7179277/terminator_02-2.smt2_1.txt)
![image](https://user-images.githubusercontent.com/16242682/133646009-9c8073e0-0240-499f-a9d3-742d8ecab158.png)
[terminator_02-2.smt2_2.txt](https://github.com/izlatkin/HornLauncher/files/7179293/terminator_02-2.smt2_2.txt)

**Comment by izlatkin** [comment]
return x => return rand()
![image](https://user-images.githubusercontent.com/16242682/134223318-3db9e8ce-3d44-4cb7-a56b-307a30925657.png)
[terminator_02-2_return.smt2.txt](https://github.com/izlatkin/HornLauncher/files/7205247/terminator_02-2_return.smt2.txt)

Coverage diff
![image](https://user-images.githubusercontent.com/16242682/134223886-8e4b888d-cb2f-4ffc-9183-ceaee340bb87.png)
![image](https://user-images.githubusercontent.com/16242682/134223911-9548b165-1086-4484-bea0-058d39fd2833.png)

**Comment by izlatkin** [comment]
fix, SeaHorn bug related to `Error: key \d+ not found`
